spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: username
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none



